Dev
stepancar-web-programming/2023-fall-lab-portfolio-aplavina-a.-a. pull request #1
Opened 2023-11-14 20:52 UTC by AnnaAplavina

Pull request for review

2023-11-15 15:49 UTC, stepancar commented
@AnnaAplavina , добрый день. Пр Не готов к ревью, пожалуйста исправьте конфликты

2023-11-15 15:52 UTC, stepancar commented on src/styles/reset.css
> +}
Пожалуйста, сделайте ПР готовым к ревью.
Отформатируйте код согласно вашим же гайдлайнам.
Вижу в этом файле 3 стиля форматирования

2023-11-15 15:54 UTC, stepancar commented on src/styles/reset.css
> +    /* color: inherit; */
Пожалуйста, убедитесь в том, что код готов к ревью.

2023-11-15 15:59 UTC, stepancar commented on public/logo192.png
Пожалуйста, убедитесь что ПР содержит все необходимые файлы и ничего лишнего

2023-11-15 15:59 UTC, stepancar requested changes
Не выполнены минимальные требования

2023-11-16 09:37 UTC, AnnaAplavina commented on src/styles/reset.css
> +}
Поправила

2023-11-16 09:38 UTC, AnnaAplavina commented on src/styles/reset.css
> +    /* color: inherit; */
Убрала комментарии

2023-11-16 09:38 UTC, AnnaAplavina commented on public/logo192.png
Лишнее удалила

2023-11-22 16:59 UTC, AnnaAplavina commented
Все исправила

2023-12-06 23:27 UTC, stepancar commented on src/pages/home/Home.js
> +                project that brings theory to practice.
👍

2023-12-06 23:31 UTC, stepancar commented on src/components/footer/Footer.js
> +            <a href="">
Добавьте валидный email (не обязательно ваш) и сделайте эту ссылку таким образом, чтобы при нажатии на нее открывался почтовый клиент по умолчанию

2023-12-06 23:34 UTC, stepancar commented on src/components/slider/Slider.js
> +    postgresSkill,
Давайте представим, что ваше портфолио рассматривает компания, которая разрабатывает софт для людей с ограниченными возможностями. Чтобы поддержать таких людей, выделен большой бюджет. Вас пытается нанять человек с этого видео https://www.youtube.com/watch?v=RQiN1Hhrxu0.

Однако, он не сможет просмотреть ваши навыки, так как это картинки. как ему помочь?

2023-12-06 23:36 UTC, stepancar requested changes
Давайте на защиту поработаем над accessability

2024-01-02 09:14 UTC, AnnaAplavina commented
Все сделала

2024-01-04 03:52 UTC, stepancar requested changes
Кнопки и ссылки не акцессабильны, на них нельзя навестись табом,

https://web-portfolio-react-aplavina.netlify.app/skills
переход по прямой ссылке не работает.
Воспроизвести можно открыв вашу страницу https://web-portfolio-react-aplavina.netlify.app/ перейти в раздел скилов, перейти по ссылке и вернуться назад через навигацию в браузере

2024-01-04 09:58 UTC, AnnaAplavina commented
Теперь все интерактивные элементы можно выбрать табом. Для наглядности добавила им красную рамку при выборе. Пофиксила проблему с возвратом на сайт через навигацию в браузере.

2024-01-07 06:05 UTC, stepancar approved these changes

2024-01-07 06:06 UTC, merged